_target_: chimera.models.basic_module.ClassificationLit

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0001
  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: chimera.models.hyena.HyenaDna
  number_of_classes: 2
  backbone_name: "hyenadna-small-32k-seqlen"
  freeze_backbone: false
  head:
    _target_: chimera.models.hyena.BinarySequenceClassifier
    input_dim: 256
    hidden_dim: 512
    num_layers: 2
    dropout: 0.1
    pooling_type: "attention"
    activation: "gelu"
    use_residual: true

criterion:
  _target_: torch.nn.CrossEntropyLoss

# compile model for faster training with pytorch 2.0
compile: false
