defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_f1_{val/f1:.4f}"
  monitor: "val/f1"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False


early_stopping:
  monitor: "val/f1"
  patience: 40
  mode: "max"

write:
  _target_: chimera.models.callbacks.CustomWriter
  output_dir: ${paths.output_dir}/predicts
  write_interval: "batch" # epoch batch batch_and_epoch
