# @package _global_

defaults:
  - _self_
  - data: fq # choose datamodule with `test_dataloader()` for evaluation
  - model: mambasp
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  - callbacks: default

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
